from fastapi import HTTPException, status
from pydantic import ValidationError
from src.database.models.search_model import IndexResponse
from src.services.embedding_service import embedding_service
from src.services.vector_service import vector_service
import logging


logger = logging.getLogger(__name__)


async def index_producer(producer_id: str, ai_profile_data: str, region: str, certifications: list, primary_crops: list) -> IndexResponse:
    """
    Indexes a producer's information and their AI-generated profile into pgvector.
    Embedding is generated by the orchestration service, then stored in Postgres.
    """
    try:
        # 1. Get producer by ID


        # 2. Get AI profile by user_id - Calling the provided function

        logger.info(f"AI Profile Data: {ai_profile_data}")
        if not ai_profile_data:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=f"AI profile for producer ID '{producer_id}' not found via external function call."
            )

        # Combine relevant text for vectorization
        text_to_embed = (
            f"AI Profile: {ai_profile_data}"
        )

        embedding_vector = embedding_service.get_embedding(text_to_embed)

        metadata = {
            "region": region,
            "certifications": certifications,
            "primary_crops": primary_crops,
            "producer_id": producer_id, # Storing producer_id as metadata for filtering

        }

        await vector_service.upsert(str(producer_id), embedding_vector, metadata)

        return IndexResponse(
            success=True,
            message=f"Producer '{producer_id}' successfully indexed.",
            indexed_id=producer_id
        )

    except HTTPException as e:
        raise e
    except ValidationError as e:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=f"Data validation error during indexing: {e.errors()}"
        )
    except Exception as e:
        print(f"Error during indexing for producer ID '{producer_id}': {e}")
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An unexpected error occurred during indexing for producer '{producer_id}': {str(e)}"
        )
