import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Chatbot from "@/components/chatbot/chatbot";
import { QueryClientProvider } from "@tanstack/react-query";
import queryClient from "@/lib/query/queryClient";

const roboto = Roboto({
	variable: "--font-roboto",
	subsets: ["latin"],
});

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<QueryClientProvider client={queryClient}>
			<html lang="en">
				<body
					className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} antialiased`}
				>
					<Chatbot />
					{children}
				</body>
			</html>
		</QueryClientProvider>
	);
}
